services:
  polybot:
    image: ${POLYBOT_IMG_NAME}
    container_name: polybot
    restart: always
    ports:
      - "8443:8443"
    environment:
      - TELEGRAM_APP_URL=${TELEGRAM_APP_URL}
      - BUCKET_NAME=${BUCKET_NAME}

  yolo:
    image: ${YOLO_IMG_NAME}
    container_name: yolo
    restart: always
    ports:
      - "8081:8081"
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
